// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://etmorjjozxeshqlmmsxu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV0bW9yampvenhlc2hxbG1tc3h1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMTUzNzEsImV4cCI6MjA2MzU5MTM3MX0.Vk-e6FAjWJvDuw99DUW5SIubyGq9ZsbxxvU_mCsi1C8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});